---
- name: Deploy to Tomcat
  hosts: web
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MymavenWebApp01/target/MymavenWebApp01.war"
        dest: "/opt/tomcat/webapps/MymavenWebApp01.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
